---
title: "LPA"
output: html_document
---

```{r setup, include=FALSE}
# load packages
packages <- c("tidyverse", "tidyLPA", "here")

purrr::map(packages, library, character.only = TRUE)

# load data
d <- read_csv(here("data/210312_dyad_data.csv")) %>% 
  rename(prop_female = prop.female, emotion_acc = emotion.acc) %>% 
  filter(!is.na(grp_conf_factor)) # remove groups with missing values for conf and acc factors

# age, aus.born, eng.fl, adapt.affective:emotion.acc, 
x <- d %>% select(grp_accuracy_cfa, grp_confidence_cfa, ind_accuracy_cfa, ind_confidence_cfa,
                  # prop_female, emotion_acc, speak_duration, speak_ratio, mean.disagree, trust)
                  adapt.affective, adapt.cognitive, adapt.global, wm.acc, risk.aversion)
                  # agreeableness, conscientiousness, extraversion, intellect, neuroticism)


# missing value analysis --------------------------------------------------
# % missing values for each variable
naniar::gg_miss_var(x, show_pct = TRUE)

# there can't be any missing values in the dataset for LPA
# so let's impute missing values
x <- mclust::imputeData(x) %>% as_tibble()
```


```{r lpa}

# which models to fit?
mods <- c(1:3,6)

fit <- x %>%
  scale() %>% # standardise variables to aid interpretation from profile plots
  estimate_profiles(2:6, # set the number of profiles to extract
                    models = mods) %>%
                    # variances = c("equal", "varying", "equal", "varying"), # set how variances are treated - determines the model type
                    # covariances = c("zero", "zero", "equal", "varying")) %>%  # set how covariances are treated - determines the model type
  compare_solutions(statistics = c("AIC", "BIC", "Entropy")) # select the goodness of fit stats to compare models. See documentation for full list.

fit$fits %>%
  select(Model, Classes, AIC, BIC, SABIC, Entropy, LogLik) %>%
  mutate(across(where(is.numeric), round, 3))


# fits <- fit$fits %>% 
#   filter(Entropy > .8)
```

``` {r fit}

fit <- map(mods, function(m) {
  map(2:4, function(p) {
    fit <- x %>%
      scale() %>%
      estimate_profiles(models = m,
                        n_profiles = p)
  })
})


# prop_class <- function(fit) {
#   get_data(fit) %>%
#     select(Class) %>% table()/nrow(x)
# }
# 
# prop_class(fit)

```


``` {r plot}
# lpa_est <- map(c(1:4), function(m) {
#   map(1:3, function(p) {
#   get_estimates(fit[[m]][[p]])
# })
# })
# 
# bind_rows(lpa_est) %>%
#   filter(Category == "Means") %>%
#   select(Model, Classes, Parameter, Estimate, se, Class) %>% 
#   mutate(Class = factor(Class),
#          Parameter = factor(Parameter)) %>% 
#   ggplot(aes(x = Parameter, y = Estimate, group = Class)) +
#   geom_line(aes(linetype = Class, colour = Class)) +
#   geom_errorbar(aes(ymin = Estimate - se, ymax = Estimate + se, colour = Class),
#                 width = .1) +
#   facet_grid(Model ~ Classes) +
#   labs(x = "Variable",
#        y = "Mean") +          
#   theme_classic() +
#   theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

  

```